"""Initial schema with 7 core tables and pgvector

Revision ID: 22fa123f9fc4
Revises: 
Create Date: 2026-09-06 21:55:36.988272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '22fa123f9fc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPERVISOR', 'PLANNER', 'ADMIN', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('wbs_code', sa.String(length=100), nullable=True),
    sa.Column('activity_name', sa.String(length=500), nullable=False),
    sa.Column('discipline', sa.Enum('CIVIL', 'PIPING', 'ELECTRICAL', 'INSTRUMENTATION', 'HSE', 'OTHER', name='discipline_enum', native_enum=False), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_discipline'), ['discipline'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_status'), ['status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('PDF', 'XLSX', 'TEXT', 'SCAN', 'VOICE', name='source_type_enum', native_enum=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('activity_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_embeddings_activity_id'), ['activity_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_activity_embeddings_id'), ['id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False, comment='Embedding similarity score'),
    sa.Column('entity_score', sa.Float(), nullable=False, comment='Exact/fuzzy entity match score'),
    sa.Column('metadata_score', sa.Float(), nullable=False, comment='WBS/context consistency score'),
    sa.Column('final_confidence', sa.Float(), nullable=False, comment='Weighted sum: >0.90 auto, 0.70-0.90 review, <0.70 rejected'),
    sa.Column('decision', sa.Enum('AUTO', 'REVIEW', 'REJECTED', name='decision_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_report_id'), ['report_id'], unique=False)

    op.create_table('progress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('source_report_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('START', 'FINISH', name='event_type_enum', native_enum=False), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_events_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_events_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_events_source_report_id'), ['source_report_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_event_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['progress_event_id'], ['progress_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_progress_event_id'), ['progress_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_progress_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor'))

    op.drop_table('audit_log')
    with op.batch_alter_table('progress_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_events_source_report_id'))
        batch_op.drop_index(batch_op.f('ix_progress_events_id'))
        batch_op.drop_index(batch_op.f('ix_progress_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_progress_events_approved_by'))
        batch_op.drop_index(batch_op.f('ix_progress_events_activity_id'))

    op.drop_table('progress_events')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_report_id'))
        batch_op.drop_index(batch_op.f('ix_matches_id'))
        batch_op.drop_index(batch_op.f('ix_matches_decision'))
        batch_op.drop_index(batch_op.f('ix_matches_activity_id'))

    op.drop_table('matches')
    with op.batch_alter_table('activity_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_embeddings_id'))
        batch_op.drop_index(batch_op.f('ix_activity_embeddings_activity_id'))

    op.drop_table('activity_embeddings')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_reports_source_type'))
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_status'))
        batch_op.drop_index(batch_op.f('ix_activities_project_id'))
        batch_op.drop_index(batch_op.f('ix_activities_parent_id'))
        batch_op.drop_index(batch_op.f('ix_activities_id'))
        batch_op.drop_index(batch_op.f('ix_activities_discipline'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_id'))

    op.drop_table('activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
