"""add_historical_activities_table

Revision ID: 9f52d3f74271
Revises: 22fa123f9fc4
Create Date: 2026-09-07 00:48:05.484459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '9f52d3f74271'
down_revision: Union[str, Sequence[str], None] = '22fa123f9fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('activity_name', sa.String(length=500), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('pipe_diameter_in', sa.Float(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('planned_duration_days', sa.Integer(), nullable=True),
    sa.Column('actual_duration_days', sa.Integer(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('delay_reason', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_activities_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_activities_discipline'), ['discipline'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_activities_pipe_diameter_in'), ['pipe_diameter_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_activities_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)

    with op.batch_alter_table('activity_embeddings', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_embeddings', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=sa.NUMERIC(precision=384),
               existing_nullable=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=sa.NUMERIC(precision=384),
               existing_nullable=True)

    with op.batch_alter_table('historical_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_activities_project_id'))
        batch_op.drop_index(batch_op.f('ix_historical_activities_pipe_diameter_in'))
        batch_op.drop_index(batch_op.f('ix_historical_activities_id'))
        batch_op.drop_index(batch_op.f('ix_historical_activities_discipline'))
        batch_op.drop_index(batch_op.f('ix_historical_activities_activity_id'))

    op.drop_table('historical_activities')
    # ### end Alembic commands ###
